---
- name: Restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted

- name: Restart Apache
  ansible.builtin.systemd:
    name: httpd
    state: restarted

# Made with Bob
